### ISSUE TITLE
mordo

### ISSUE THREAD

**Issue by Memexurer** [ENDERM4NQ/DmAll#1]
mordo to ci nie zadziala, zwykly wrapper api discorda nie jest pod selfboty
uzyj cos typu discord sCUM zebys mogl zrobic dmall

pozdro, z fartem

**Comment by ENDERM4NQ** [comment]
Dzięki, aczkolwiek działa.

**Comment by Memexurer** [comment]
Działa, bo to tylko do znajomych wysyła wiadomości xD
Używając wrappera który nie jest pod selfboty już ci nie zadziała wysyłanie wiadomości do "wszystkich"
